Owner: JJGGu
Platform: github
ServiceType: private
Branch: main
AllowedRegions:
- ap-southeast-1
ArtifactSourceType: DockerCompose
RepoName: JJGGu/dify-test
DockerComposeEnvPath: docker/.env.example
RegionId: cn-hangzhou
CustomParameters: ''
DockerComposeYamlPath: docker/docker-compose.yaml
